name: dart_melty_soundfont
description: A Soundfont synthesizer (i.e. '.sf2' player) written in pure Dart.
version: 1.1.9
homepage: https://github.com/chipweinberger/dart_melty_soundfont


environment:
  sdk: '>=2.12.0 <4.0.0'
